services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json    
    volumes:
      - ./frontend:/app
      - /app/node_modules
